name: "Publish"
on:
  push:
    branches:
      - master
jobs:
  neuron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build neuron site 🔧
      run: |
        mkdir -p .neuron/output && touch .neuron/output/.nojekyll
        docker run -v $PWD:/notes sridca/neuron neuron gen
    - name: Deploy to gh-pages 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .neuron/output/
        cname: politicalnotes.org
